# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=30)),
                ('fechaNacimiento', models.DateField()),
                ('ciudadNacimiento', models.IntegerField()),
                ('ciudadActual', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('numeroDocumento', models.BigIntegerField()),
            ],
        ),
    ]
